# Generated by Django 3.0.3 on 2020-02-13 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GMapLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('locality', models.CharField(blank=True, max_length=40)),
                ('district', models.CharField(blank=True, max_length=40)),
                ('state', models.CharField(blank=True, max_length=40)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('lat', models.CharField(blank=True, max_length=20)),
                ('lng', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='images/', verbose_name='Profile Pic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=50)),
                ('summary', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userprofile.GMapLocation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
